# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.

# Basic Site Settings
locale: "en-US"
site_theme: "default"
title: "Anastasis Georgiou | PhD Student in Mechanical Engineering"
title_separator: "|"
name: "Anastasis Georgiou"
description: "Mechanical and Aerospace Engineer researching heat transfer modelling, composite materials, and space weathering effects. PhD candidate at Memorial University of Newfoundland."
url: "https://apgeorgiou.github.io"
baseurl: ""
repository: "a-georgiou19/apgeorgiou.github.io"

# Site Author
author:
  # Biographic information
  avatar: "/assets/images/profile.png"
  name: "Anastasis Georgiou"
  pronouns: "He/Him"
  bio: "PhD Candidate researching atomistic modelling of materials and planetary surface processes"
  location: "St. John's, NL, Canada"
  employer: "Memorial University of Newfoundland"
  email: "apgeorgiou@mun.ca"

  # Academic websites
  googlescholar: "https://scholar.google.com/citations?user=09V3OK88yMQC&hl=en"
  orcid: "https://orcid.org/0009-0003-4022-0681"

  # Repositories and software development
  github: "a-georgiou19"

  # Social media
  linkedin: "https://uk.linkedin.com/in/anastasis-georgiou"

# Publication Categories
publication_category:
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser: "/assets/images/teaser.jpg"
breadcrumbs: false
words_per_minute: 160
future: false
read_more: "disabled"
talkmap_link: false
comments:
  provider: false

atom_feed:
  hide: false
  path: "feed.xml"

# Social Sharing
twitter:
  username:
og_image: "/assets/images/social-preview.jpg"
og_description: "Anastasis Georgiou - PhD Student in Mechanical Engineering researching atomistic modelling and space materials"

# For specifying social profiles
social:
  type: Person
  name: "Anastasis Georgiou"
  links:
    - "https://uk.linkedin.com/in/anastasis-georgiou"
    - "https://scholar.google.com/citations?user=09V3OK88yMQC&hl=en"
    - "https://orcid.org/0009-0003-4022-0681"

# Analytics
analytics:
  provider: false
  google:
    tracking_id:

# Reading Files
include:
  - _pages
  - _posts
  - _publications
  - _teaching
  - _talks
  - _portfolio
  - files
  - assets

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json
  - Rakefile
  - README.md
  - tmp
  - vendor

keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /teaching/:path/
  publications:
    output: true
    permalink: /publications/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/
  talks:
    output: true
    permalink: /talks/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      share: true
      read_time: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/St_Johns

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Mimic GitHub Pages with --safe
whitelist:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Custom variables
github_username: a-georgiou19
